name: Welcome

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  greeting:
    permissions:
      issues: write  # for actions/first-interaction to comment on first issue
      pull-requests: write  # for actions/first-interaction to comment on first PR
    if: github.repository == 'WebGoat/WebGoat'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for submitting your first issue, we will have a look as quickly as possible.'
          pr-message: 'Thanks so much for your contribution, really appreciated! We will have a look and merge it if everything checks out!'
